apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  ports:
    - name: adminer
      port: 8080
  selector:
    app: adminer
    env: dev
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  selector:
    matchLabels:
      app: adminer
      env: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adminer
        env: dev
    spec:
      containers:
        - image: adminer
          name: adminer-ctn
          ports:
            - containerPort: 8080
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-passthrough
spec:
  type: NodePort
  selector:
    app: adminer
    env: dev
  ports:
    - name: passthrough-adminer
      nodePort: 30080
      protocol: TCP
      port: 8080
      targetPort: 8080
