apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - name: mysql
      port: 3306
  selector:
    app: mysql
    env: dev
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      env: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        env: dev
    spec:
      containers:
        - image: mysql:5.6
          name: mysql-ctn
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: # Replace with an amazing password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-passthrough
spec:
  type: NodePort
  selector:
    app: mysql
    env: dev
  ports:
    - name: passthrough-mysql
      nodePort: 32306
      protocol: TCP
      port: 3306
      targetPort: 3306
---
